### ISSUE TITLE
Role Admin

### ISSUE THREAD

**Issue by UKha11** [noobiesdev/kedele#6]
# Reproduksi 
## Mengubah kata sandi 
bug kata sandi lama tidak terdefinisi
"Undefined index: old_password"

**Comment by UKha11** [comment]
## Menambahkan data pengguna
- Kolom alamat tidak ada didalam database table user
"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'alamat' in 'field list' (SQL: insert into `user` (`nama`, `username`, `email`, `no_hp`, `password`, `level`, `alamat`, `updated_at`, `created_at`) values (pembeli2, pembeli2, pembeli2@gmail.com, 6257836861718, $2y$10$9kECKV6iEqtS.1fPNk7lEugzvZzcQKgp7nYzEvM5VE/gSfHXqUkVS, konsumen, talangsari, 2020-12-16 14:57:32, 2020-12-16 14:57:32))

**Comment by UKha11** [comment]
## Mengubah data pengguna
- kolom alamat tidak ada didalam database table user
"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'alamat' in 'field list' (SQL: update `user` set `password` = $2y$10$Elytumu5tI8fkYGdW4FN6.J0c4OGdZJFddUlNCHfDcklpAHr.Ckm6, `alamat` = talangsari, `user`.`updated_at` = 2020-12-16 15:04:54 where `id` = 1)

**Comment by darkun7** [comment]
Database belum dilakukan migrasi, harap jalankan perintah `php artisan migrate:fresh --seed`
